package com.shiro.flashsale.service;

import com.shiro.flashsale.config.AppProperties;
import com.shiro.flashsale.constants.PurchaseStatus;
import com.shiro.flashsale.constants.ServiceConstants;
import com.shiro.flashsale.dto.SaleDtos;
import com.shiro.flashsale.dto.client.PaymentResult;
import com.shiro.flashsale.entity.FlashSaleItem;
import com.shiro.flashsale.entity.Purchase;
import com.shiro.flashsale.exception.ApiException;
import com.shiro.flashsale.exception.ErrorCode;
import com.shiro.flashsale.exception.PurchaseResponseException;
import com.shiro.flashsale.repository.FlashSaleItemQuotaRepository;
import com.shiro.flashsale.repository.PurchaseRepository;
import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

@Service
@AllArgsConstructor
public class PurchaseExecuter {
  private static final Logger log = LoggerFactory.getLogger(PurchaseExecuter.class);
  private final PurchaseRepository purchases;
  private final FlashSaleItemQuotaRepository quotas;
  private final EntityManager entityManager;
  private final WarehouseService warehouse;
  private final PaymentService payment;
  private final PurchasePersistenceService purchasePersistence;
  private final AppProperties properties;

  @Transactional
  public SaleDtos.PurchaseResponse execute(UUID userId, FlashSaleItem item, LocalDate saleDate) {
    Instant now = Instant.now();
    FlashSaleItem itemRef = entityManager.getReference(FlashSaleItem.class, item.getId());
    Purchase purchase = new Purchase(userId, itemRef, item.getAmount(), saleDate, now);

    preValidate(item, userId, saleDate);

    purchase = purchasePersistence.createPending(purchase);
    // The UUID is generated by Hibernate when the entity is persisted/flushed.
    String reservationKey = purchase.getId().toString();

    reserveProcess(purchase, item, userId, reservationKey, saleDate);
    return confirmProcess(purchase, item, reservationKey, saleDate);
  }

  private void preValidate(FlashSaleItem item, UUID userId, LocalDate saleDate) {
    if (purchases.countByCustomerIdAndPurchaseDateAndStatusIsNot(
            userId, saleDate, PurchaseStatus.FAILED)
        >= properties.getSale().getLimitDailyPurchase()) {
      log.warn(
          "Purchase rejected: daily limit reached, userId={}, itemId={}", userId, item.getId());
      throw ApiException.of(ErrorCode.DAILY_LIMIT_REACHED);
    }
    // Todo check if user has enough balance
  }

  private void reserveProcess(
      Purchase purchase,
      FlashSaleItem item,
      UUID userId,
      String reservationKey,
      LocalDate saleDate) {

    PaymentResult pending;
    try {
      // Send payment pending request
      pending =
          payment.pending(
              purchase.getId(), userId, item.getProduct().getOwnerId(), item.getAmount());
      if (!pending.success() || !PurchaseStatus.PENDING.name().equals(pending.status())) {
        // Failed to update purchase status after payment pending rejection
        purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.FAILED);
        log.warn("Purchase rejected during payment pending, purchaseId={}", purchase.getId());
        throw ApiException.of(ErrorCode.PAYMENT_FAILED);
      }
    } catch (ApiException e) {
      throw e;
    } catch (Exception e) {
      log.error("Failed to send payment pending request, purchaseId={}", purchase.getId(), e);
      throw ApiException.of(ErrorCode.PAYMENT_FAILED);
    }

    try {
      initReservation(purchase, item, pending, reservationKey, saleDate);
    } catch (Exception failure) {
      log.error(
          "Reservation process failed, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId(),
          failure);
      releaseReservation(purchase, item, reservationKey);
      throw failure;
    }
  }

  private SaleDtos.PurchaseResponse confirmProcess(
      Purchase purchase, FlashSaleItem item, String reservationKey, LocalDate saleDate) {
    try {
      // Commit payment
      PaymentResult confirmed = payment.confirm(purchase.getId());
      // Mark failed purchase as pending if payment failed
      if (!confirmed.success() || !ServiceConstants.COMPLETE.equals(confirmed.status())) {
        releaseReservation(purchase, item, reservationKey);
        throw new PurchaseResponseException(failedResponse(purchase, item, saleDate));
      }
      // Commit purchase to warehouse and update status
      confirmReservation(purchase, item, reservationKey);
    } catch (PurchaseResponseException e) {
      throw e;
    } catch (Exception e) {
      log.error(
          "Failed to confirm purchase, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId(),
          e);
      throw new PurchaseResponseException(pendingResponse(purchase, item, saleDate));
    }
    return successResponse(purchase, item, saleDate);
  }

  private void initReservation(
      Purchase purchase,
      FlashSaleItem item,
      PaymentResult pending,
      String reservationKey,
      LocalDate saleDate) {
    purchasePersistence.paymentPending(purchase.getId(), pending.transactionId());
    warehouse.reserve(item.getProduct().getId(), reservationKey);
    if (quotas.decrement(item.getId().toString(), 1, saleDate) == 0) {
      log.warn(
          "Purchase rejected: item sold out, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId());
      throw ApiException.of(ErrorCode.SOLD_OUT);
    }
  }

  private void releaseReservation(Purchase purchase, FlashSaleItem item, String reservationKey) {
    try {
      purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.FAILED);
      payment.cancel(purchase.getId());
      warehouse.release(reservationKey, item.getProduct().getId());
    } catch (RuntimeException e) {
      log.error("Failed when release reservation, purchaseId={}", purchase.getId(), e);
    }
  }

  private void confirmReservation(Purchase purchase, FlashSaleItem item, String reservationKey) {
    try {
      purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.SUCCESS);
      warehouse.sold(item.getProduct().getId(), reservationKey);
    } catch (RuntimeException e) {
      log.error("Failed when confirm reservation, purchaseId={}", purchase.getId(), e);
    }
  }

  private SaleDtos.PurchaseResponse successResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase,
        item,
        saleDate,
        PurchaseStatus.SUCCESS,
        ServiceConstants.PURCHASE_SUCCESS_MESSAGE);
  }

  private SaleDtos.PurchaseResponse failedResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase, item, saleDate, PurchaseStatus.FAILED, ServiceConstants.PAYMENT_FAILED);
  }

  private SaleDtos.PurchaseResponse pendingResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase, item, saleDate, PurchaseStatus.PENDING, ServiceConstants.PAYMENT_RETRY_MESSAGE);
  }

  private SaleDtos.PurchaseResponse purchaseResponse(
      Purchase purchase,
      FlashSaleItem item,
      LocalDate saleDate,
      PurchaseStatus status,
      String message) {
    return new SaleDtos.PurchaseResponse(
        purchase.getId(),
        item.getId(),
        item.getProduct().getSku(),
        item.getAmount(),
        saleDate,
        status.name(),
        message);
  }
}
