package com.shiro.flashsale.service;

import com.shiro.flashsale.constants.PurchaseStatus;
import com.shiro.flashsale.constants.ServiceConstants;
import com.shiro.flashsale.dto.SaleDtos;
import com.shiro.flashsale.dto.client.PaymentDtos;
import com.shiro.flashsale.entity.FlashSaleItem;
import com.shiro.flashsale.entity.Purchase;
import com.shiro.flashsale.exception.ApiException;
import com.shiro.flashsale.exception.ErrorCode;
import com.shiro.flashsale.exception.PurchaseResponseException;
import com.shiro.flashsale.repository.FlashSaleItemQuotaRepository;
import com.shiro.flashsale.repository.PurchaseRepository;
import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/** Orchestrates the reservation, payment, and completion steps of a purchase. */
@Service
@AllArgsConstructor
public class PurchaseExecuter {
  private static final Logger log = LoggerFactory.getLogger(PurchaseExecuter.class);
  private final PurchaseRepository purchases;
  private final FlashSaleItemQuotaRepository quotas;
  private final EntityManager entityManager;
  private final WarehouseService warehouse;
  private final PaymentService payment;
  private final PurchasePersistenceService purchasePersistence;
  private final CacheConfigService cacheConfigService;
  private final RedisService redisService;
  private final com.shiro.flashsale.config.AppProperties properties;

  @Transactional
  public SaleDtos.PurchaseResponse execute(
      UUID userId, FlashSaleItem item, Integer quantity, LocalDate saleDate) {
    Instant now = Instant.now();
    FlashSaleItem itemRef = entityManager.getReference(FlashSaleItem.class, item.getId());
    Purchase purchase = new Purchase(userId, itemRef, item.getAmount(), saleDate, now);

    preValidate(item, userId, saleDate);

    purchase = purchasePersistence.createPending(purchase);
    // The UUID is generated by Hibernate when the entity is persisted/flushed.
    UUID reservationKey = purchase.getId();

    reserveProcess(purchase, item, userId, reservationKey, quantity, saleDate);
    return confirmProcess(purchase, item, reservationKey, quantity, saleDate);
  }

  private void preValidate(FlashSaleItem item, UUID userId, LocalDate saleDate) {
    if (purchases.countByCustomerIdAndPurchaseDateAndStatusIsNot(
            userId, saleDate, PurchaseStatus.FAILED)
        >= cacheConfigService.getLimitDailyPurchase()) {
      log.warn(
          "Purchase rejected: daily limit reached, userId={}, itemId={}", userId, item.getId());
      throw ApiException.of(ErrorCode.DAILY_LIMIT_REACHED);
    }
    // Todo check if user has enough balance
  }

  private void reserveProcess(
      Purchase purchase,
      FlashSaleItem item,
      UUID userId,
      UUID reservationKey,
      Integer quantity,
      LocalDate saleDate) {
    checkAndConsumeQuota(purchase, item, quantity, saleDate);
    PaymentDtos.Response pending = createPendingPayment(purchase, item, userId);
    updateStatusAndReserveWarehouse(purchase, item, pending, reservationKey, quantity);
  }

  /** Uses Redis as a fast quota guard and the database as the source of truth. */
  private void checkAndConsumeQuota(
      Purchase purchase, FlashSaleItem item, Integer quantity, LocalDate saleDate) {
    var consumedQuotas = quotas.decrement(item.getId().toString(), quantity, saleDate);
    if (consumedQuotas == 0) {
      log.warn(
          "Purchase rejected: item sold out, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId());
      throw ApiException.of(ErrorCode.SOLD_OUT);
    }
  }

  /** Requests a payment hold for the purchase. */
  private PaymentDtos.Response createPendingPayment(
      Purchase purchase, FlashSaleItem item, UUID userId) {
    try {
      PaymentDtos.Response pending =
          payment.pending(
              purchase.getId(), userId, item.getProduct().getOwnerId(), item.getAmount());
      if (!pending.isSuccess() || !PaymentDtos.PaymentStatus.PENDING.equals(pending.getStatus())) {
        purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.FAILED);
        log.warn("Purchase rejected during payment pending, purchaseId={}", purchase.getId());
        throw ApiException.of(ErrorCode.PAYMENT_FAILED);
      }
      return pending;
    } catch (ApiException e) {
      throw e;
    } catch (Exception e) {
      log.error("Failed to send payment pending request, purchaseId={}", purchase.getId(), e);
      throw ApiException.of(ErrorCode.PAYMENT_FAILED);
    }
  }

  /** Persists the payment transaction and reserves the product in Warehouse. */
  private void updateStatusAndReserveWarehouse(
      Purchase purchase,
      FlashSaleItem item,
      PaymentDtos.Response pending,
      UUID reservationKey,
      Integer quantity) {
    try {
      purchasePersistence.paymentPending(purchase.getId(), pending.getTransactionId());
      warehouse.reserve(item.getProduct().getId(), reservationKey, quantity);
    } catch (Exception failure) {
      log.error(
          "Reservation process failed, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId(),
          failure);
      releaseReservation(purchase, item, reservationKey);
      throw failure;
    }
  }

  private SaleDtos.PurchaseResponse confirmProcess(
      Purchase purchase,
      FlashSaleItem item,
      UUID reservationKey,
      Integer quantity,
      LocalDate saleDate) {
    try {
      // Confirm payment
      PaymentDtos.Response confirmed = payment.confirm(purchase.getId());
      if (!confirmed.isSuccess()
          || !PaymentDtos.PaymentStatus.COMPLETE.equals(confirmed.getStatus())) {
        // Mark failed if payment failed, throw error to roll back
        releaseReservation(purchase, item, reservationKey);
        throw new PurchaseResponseException(failedResponse(purchase, item, saleDate));
      }
      // Confirm purchase to warehouse and update status
      confirmReservation(purchase, item, reservationKey);
    } catch (PurchaseResponseException e) {
      throw e;
    } catch (Exception e) {
      log.error(
          "Failed to confirm purchase, purchaseId={}, itemId={}",
          purchase.getId(),
          item.getId(),
          e);
      // Mark pending if payment failed, waiting job check status
      return pendingResponse(purchase, item, saleDate);
    }
    return successResponse(purchase, item, saleDate);
  }

  private void releaseReservation(Purchase purchase, FlashSaleItem item, UUID reservationKey) {
    try {
      purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.FAILED);
      payment.cancel(purchase.getId());
      warehouse.release(reservationKey, item.getProduct().getId());
    } catch (RuntimeException e) {
      log.error("Failed when release reservation, purchaseId={}", purchase.getId(), e);
    }
  }

  private void confirmReservation(Purchase purchase, FlashSaleItem item, UUID reservationKey) {
    try {
      purchasePersistence.updateStatus(purchase.getId(), PurchaseStatus.SUCCESS);
      warehouse.sold(item.getProduct().getId(), reservationKey);
    } catch (RuntimeException e) {
      log.error("Failed when confirm reservation, purchaseId={}", purchase.getId(), e);
    }
  }

  private SaleDtos.PurchaseResponse successResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase,
        item,
        saleDate,
        PurchaseStatus.SUCCESS,
        ServiceConstants.PURCHASE_SUCCESS_MESSAGE);
  }

  private SaleDtos.PurchaseResponse failedResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase, item, saleDate, PurchaseStatus.FAILED, ServiceConstants.PAYMENT_FAILED);
  }

  private SaleDtos.PurchaseResponse pendingResponse(
      Purchase purchase, FlashSaleItem item, LocalDate saleDate) {
    return purchaseResponse(
        purchase, item, saleDate, PurchaseStatus.PENDING, ServiceConstants.PAYMENT_RETRY_MESSAGE);
  }

  private SaleDtos.PurchaseResponse purchaseResponse(
      Purchase purchase,
      FlashSaleItem item,
      LocalDate saleDate,
      PurchaseStatus status,
      String message) {
    return SaleDtos.PurchaseResponse.builder()
        .purchaseId(purchase.getId())
        .itemId(item.getId())
        .sku(item.getProduct().getSku())
        .amount(item.getAmount())
        .purchaseDate(saleDate)
        .status(status.name())
        .message(message)
        .build();
  }
}
